### ISSUE TITLE
dogpictur.es not found 

### ISSUE THREAD

**Issue by sometimescool22** [4Kaylum/DogAPI#1]
Hey, tried going to http://dogpictur.es and /API/v1 however I keep getting DNS not found. Just scouting around the API.

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by 4Kaylum** [comment]
Though I did mean to buy that domain, I wasn't able to. Mostly because I don't live in Spain. The site is hosted on `http://thedogapi.co.uk/`

**Comment by sometimescool22** [comment]
@4Kaylum Got it. Thanks.

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
